/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HospitalRegisterRouteImport } from './routes/hospital-register'
import { Route as HospitalDashboardRouteImport } from './routes/hospital-dashboard'
import { Route as DonorRegisterRouteImport } from './routes/donor-register'
import { Route as DonorDashboardRouteImport } from './routes/donor-dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRegisterRoute = HospitalRegisterRouteImport.update({
  id: '/hospital-register',
  path: '/hospital-register',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDashboardRoute = HospitalDashboardRouteImport.update({
  id: '/hospital-dashboard',
  path: '/hospital-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorRegisterRoute = DonorRegisterRouteImport.update({
  id: '/donor-register',
  path: '/donor-register',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDashboardRoute = DonorDashboardRouteImport.update({
  id: '/donor-dashboard',
  path: '/donor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donor-dashboard': typeof DonorDashboardRoute
  '/donor-register': typeof DonorRegisterRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/hospital-register': typeof HospitalRegisterRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donor-dashboard': typeof DonorDashboardRoute
  '/donor-register': typeof DonorRegisterRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/hospital-register': typeof HospitalRegisterRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donor-dashboard': typeof DonorDashboardRoute
  '/donor-register': typeof DonorRegisterRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/hospital-register': typeof HospitalRegisterRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donor-dashboard'
    | '/donor-register'
    | '/hospital-dashboard'
    | '/hospital-register'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donor-dashboard'
    | '/donor-register'
    | '/hospital-dashboard'
    | '/hospital-register'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donor-dashboard'
    | '/donor-register'
    | '/hospital-dashboard'
    | '/hospital-register'
    | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonorDashboardRoute: typeof DonorDashboardRoute
  DonorRegisterRoute: typeof DonorRegisterRoute
  HospitalDashboardRoute: typeof HospitalDashboardRoute
  HospitalRegisterRoute: typeof HospitalRegisterRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-register': {
      id: '/hospital-register'
      path: '/hospital-register'
      fullPath: '/hospital-register'
      preLoaderRoute: typeof HospitalRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-dashboard': {
      id: '/hospital-dashboard'
      path: '/hospital-dashboard'
      fullPath: '/hospital-dashboard'
      preLoaderRoute: typeof HospitalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor-register': {
      id: '/donor-register'
      path: '/donor-register'
      fullPath: '/donor-register'
      preLoaderRoute: typeof DonorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor-dashboard': {
      id: '/donor-dashboard'
      path: '/donor-dashboard'
      fullPath: '/donor-dashboard'
      preLoaderRoute: typeof DonorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonorDashboardRoute: DonorDashboardRoute,
  DonorRegisterRoute: DonorRegisterRoute,
  HospitalDashboardRoute: HospitalDashboardRoute,
  HospitalRegisterRoute: HospitalRegisterRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
